-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPvll4cTINGrccY0t
cnyL//DEosRDMAfwBcYREstt5mugCgYIKoZIzj0DAQehRANCAATgX0YWzQpCh1HU
ofmano6zL048Q8fQDPkBquqPI6Pl0lskflaDNW6la7+nOITKXYOpZWh+FCmxtYBQ
+6c5+3pM
-----END PRIVATE KEY-----